#### Decision Tree Regressor

In [2]:
import pandas as pd
data=pd.read_csv("headbrain.csv")
data


Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0         1          1             4512                 1530
1         1          1             3738                 1297
2         1          1             4261                 1335
3         1          1             3777                 1282
4         1          1             4177                 1590
5         1          1             3585                 1300
6         1          1             3785                 1400
7         1          1             3559                 1255
8         1          1             3613                 1355
9         1          1             3982                 1375
10        1          1             3443                 1340
11        1          1             3993                 1380
12        1          1             3640                 1355
13        1          1             4208                 1522
14        1          1             3832                 1208
15        1          1             3876                 1405
16        1          1             3497                 1358
17        1          1             3466                 1292
18        1          1             3095                 1340
19        1          1             4424                 1400
20        1          1             3878                 1357
21        1          1             4046                 1287
22        1          1             3804                 1275
23        1          1             3710                 1270
24        1          1             4747                 1635
25        1          1             4423                 1505
26        1          1             4036                 1490
27        1          1             4022                 1485
28        1          1             3454                 1310
29        1          1             4175                 1420
..      ...        ...              ...                  ...
207       2          2             3995                 1296
208       2          2             3318                 1175
209       2          2             2720                  955
210       2          2             2937                 1070
211       2          2             3580                 1320
212       2          2             2939                 1060
213       2          2             2989                 1130
214       2          2             3586                 1250
215       2          2             3156                 1225
216       2          2             3246                 1180
217       2          2             3170                 1178
218       2          2             3268                 1142
219       2          2             3389                 1130
220       2          2             3381                 1185
221       2          2             2864                 1012
222       2          2             3740                 1280
223       2          2             3479                 1103
224       2          2             3647                 1408
225       2          2             3716                 1300
226       2          2             3284                 1246
227       2          2             4204                 1380
228       2          2             3735                 1350
229       2          2             3218                 1060
230       2          2             3685                 1350
231       2          2             3704                 1220
232       2          2             3214                 1110
233       2          2             3394                 1215
234       2          2             3233                 1104
235       2          2             3352                 1170
236       2          2             3391                 1120

[237 rows x 4 columns]

In [90]:
x=data["Head Size(cm^3)"].values
x=x.reshape(-1,1)
y=data["Brain Weight(grams)"].values

In [91]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=42)
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor()
model.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [8]:
model.predict([[3391]])

array([1120.])

In [9]:
y_pred=model.predict(x_test)
y_pred

array([1280. , 1588. , 1300. , 1120. , 1520. , 1197.5, 1324. , 1027. ,
       1270. , 1130. , 1468. , 1220. , 1260. , 1290. , 1250. , 1310. ,
       1530. , 1290. , 1183.5, 1330. , 1140. , 1226. , 1335. , 1060. ,
       1192. , 1241. , 1270. , 1330. , 1229. , 1330. , 1312. , 1311. ,
       1204. , 1168. , 1330. , 1340. , 1310. , 1022. , 1130. , 1312. ,
       1250. , 1425. , 1280. , 1380. , 1355. , 1095. , 1135. , 1080. ,
       1200. , 1060. , 1290. , 1520. , 1215. , 1330. , 1468. , 1250. ,
       1241. , 1103. , 1208. , 1405. , 1520. , 1330. , 1322. , 1250. ,
       1188. , 1076. , 1330. , 1208. , 1060. , 1470. , 1440. , 1590. ])

In [82]:
from sklearn.metrics import r2_score
model.score(x_train,y_train)


0.9588706443490678

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=25)
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
model.predict([[3391]])

array([1219.89719974])

#### Random Forest Algorithm(classifier)
- related to decision tree
- disadvantage in decision tree--overfitting--model will be trained too well)


In [22]:
df=pd.read_csv("diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [24]:
x=df.iloc[:,0:8]
y=df["Outcome"]

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=42)
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [39]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [41]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.7532467532467533


###### Apply the breast cancer dataset to randomforest

In [43]:
from sklearn.datasets import load_breast_cancer
cancer=load_breast_cancer()

In [45]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [47]:
cancer.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [51]:
cancer_data=pd.DataFrame(cancer.data,columns=cancer.feature_names)
cancer_data["Target"]=cancer.target
cancer_data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  Target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [56]:
x=cancer_data.drop('Target',axis=1)

y=cancer_data["Target"]


In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=42)
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [60]:
y_pred=model.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [61]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9649122807017544


#### Randomforest Regressor

In [62]:
import pandas as pd
data=pd.read_csv("headbrain.csv")
data

Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0         1          1             4512                 1530
1         1          1             3738                 1297
2         1          1             4261                 1335
3         1          1             3777                 1282
4         1          1             4177                 1590
5         1          1             3585                 1300
6         1          1             3785                 1400
7         1          1             3559                 1255
8         1          1             3613                 1355
9         1          1             3982                 1375
10        1          1             3443                 1340
11        1          1             3993                 1380
12        1          1             3640                 1355
13        1          1             4208                 1522
14        1          1             3832                 1208
15        1          1             3876                 1405
16        1          1             3497                 1358
17        1          1             3466                 1292
18        1          1             3095                 1340
19        1          1             4424                 1400
20        1          1             3878                 1357
21        1          1             4046                 1287
22        1          1             3804                 1275
23        1          1             3710                 1270
24        1          1             4747                 1635
25        1          1             4423                 1505
26        1          1             4036                 1490
27        1          1             4022                 1485
28        1          1             3454                 1310
29        1          1             4175                 1420
..      ...        ...              ...                  ...
207       2          2             3995                 1296
208       2          2             3318                 1175
209       2          2             2720                  955
210       2          2             2937                 1070
211       2          2             3580                 1320
212       2          2             2939                 1060
213       2          2             2989                 1130
214       2          2             3586                 1250
215       2          2             3156                 1225
216       2          2             3246                 1180
217       2          2             3170                 1178
218       2          2             3268                 1142
219       2          2             3389                 1130
220       2          2             3381                 1185
221       2          2             2864                 1012
222       2          2             3740                 1280
223       2          2             3479                 1103
224       2          2             3647                 1408
225       2          2             3716                 1300
226       2          2             3284                 1246
227       2          2             4204                 1380
228       2          2             3735                 1350
229       2          2             3218                 1060
230       2          2             3685                 1350
231       2          2             3704                 1220
232       2          2             3214                 1110
233       2          2             3394                 1215
234       2          2             3233                 1104
235       2          2             3352                 1170
236       2          2             3391                 1120

[237 rows x 4 columns]

In [63]:
x=data["Head Size(cm^3)"].values
x=x.reshape(-1,1)
y=data["Brain Weight(grams)"].values

In [88]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=42)
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()
model.fit(x_train,y_train)

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [89]:
from sklearn.metrics import mean_squared_error
model.score(x_train,y_train)

0.8877512013073552